version: '3'

services:
  web:
    image: greenpen/greenpen
    command: /root/.local/bin/daphne -b 0.0.0.0 -p 8000 GreenPen.asgi:application
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - /Users/wright.j/Downloads/creds/:/root/.config/gspread/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod



volumes:
  postgres_data:
  static_volume:
  media_volume: