version: '3'
    
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
       - ./.env.dev

  web:
    image: greenpen/greenpen-full
    build: .
    env_file:
      - ./.env.dev
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /Users/wright.j/Downloads/creds/:/root/.config/gspread/

    ports:
      - "8000:8000"
    depends_on:
      - db

  jupyter:
    image: greenpen/jupyter
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - "8888:8888"
    command: start-notebook.sh
    depends_on:
      - db
    volumes:
      - ./notebooks/:/home/jovyan/notebooks/


volumes:
  postgres_data:
  service_creds: