version: '3'
    
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
       - ./.env.dev

  web:
    build: .
    env_file:
      - ./.env.dev
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /Users/wright.j/Downloads/creds/:/root/.config/gspread/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  service_creds: