# Generated by Django 3.0.6 on 2020-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='resets_ratings',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='most_recent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentsyllabusassessmentrecord',
            unique_together=set(),
        ),
    ]
