# Generated by Django 3.0.7 on 2020-06-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenPen.TeachingGroup'),
        ),
    ]
