# Generated by Django 3.0.6 on 2020-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0002_auto_20200527_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='trivital',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
