# Generated by Django 3.0.7 on 2020-08-04 10:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0002_sitting_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinggroup',
            name='year_taught',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='syllabus_points',
            field=mptt.fields.TreeManyToManyField(blank=True, to='GreenPen.Syllabus'),
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenPen.Subject'),
        ),
    ]
