# Generated by Django 3.0.6 on 2020-05-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0003_mark_trivital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='trivital',
        ),
    ]
