# Generated by Django 3.0.6 on 2020-05-20 02:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0004_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='weighting',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField()),
                ('number', models.CharField(max_length=10, unique=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Exam')),
                ('syllabus_points', mptt.fields.TreeManyToManyField(to='GreenPen.Syllabus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
