# Generated by Django 3.0.7 on 2020-08-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0005_auto_20200812_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonresources',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonresources',
            name='syllabus_points',
        ),
        migrations.AlterUniqueTogether(
            name='lessonslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonsuspension',
            name='teachinggroups',
        ),
        migrations.AlterUniqueTogether(
            name='timetabledlesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timetabledlesson',
            name='lesson_slot',
        ),
        migrations.RemoveField(
            model_name='timetabledlesson',
            name='teachinggroup',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonResources',
        ),
        migrations.DeleteModel(
            name='LessonSlot',
        ),
        migrations.DeleteModel(
            name='LessonSuspension',
        ),
        migrations.DeleteModel(
            name='TimetabledLesson',
        ),
    ]
