# Generated by Django 3.0.6 on 2020-05-20 03:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0005_auto_20200520_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Exam')),
                ('students', models.ManyToManyField(to='GreenPen.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
