# Generated by Django 3.0.6 on 2020-05-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0006_auto_20200520_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Question')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Sitting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Student')),
            ],
            options={
                'unique_together': {('student', 'question', 'sitting')},
            },
        ),
    ]
