# Generated by Django 3.0.7 on 2020-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0007_academicyear_calendaredperiod_day_period_ttslot_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='first_monday',
            field=models.DateField(help_text='This must be the first MONDAY in the school calendar year. Use suspensions if the term does not start on that monday.'),
        ),
    ]
