# Generated by Django 3.0.6 on 2020-05-21 03:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0007_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSyllabusPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Student')),
                ('syllabus_point', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Syllabus')),
            ],
            options={
                'unique_together': {('student', 'syllabus_point')},
            },
        ),
    ]
