# Generated by Django 3.0.6 on 2020-05-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0008_studentsyllabuspercent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsyllabuspercent',
            name='percentage',
        ),
        migrations.AddField(
            model_name='studentsyllabuspercent',
            name='total_marks_attempted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsyllabuspercent',
            name='total_marks_correct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
