# Generated by Django 3.0.6 on 2020-05-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0009_auto_20200521_0333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSyllabusPercent',
            new_name='StudentSyllabusRecord',
        ),
    ]
