# Generated by Django 3.0.6 on 2020-05-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0010_auto_20200521_0334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSyllabusRecord',
            new_name='StudentSyllabusAssessmentRecord',
        ),
    ]
