# Generated by Django 3.0.7 on 2020-08-14 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0010_auto_20200813_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaredperiod',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('whole_school', models.BooleanField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Period')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.CalendaredPeriod')),
                ('teachinggroups', models.ManyToManyField(to='GreenPen.TeachingGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenPen.CalendaredPeriod')),
                ('teachinggroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.TeachingGroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('teachinggroup', 'order')},
            },
        ),
    ]
