# Generated by Django 3.0.7 on 2020-08-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0011_auto_20200814_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspension',
            name='whole_school',
            field=models.BooleanField(null=True),
        ),
    ]
