# Generated by Django 3.0.6 on 2020-05-21 04:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GreenPen', '0011_auto_20200521_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSyllabusManualTeacherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 4, 0, 59, 580176))),
                ('rating', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Student')),
                ('syllabus_point', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSyllabusManualStudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 4, 0, 59, 579099))),
                ('rating', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Student')),
                ('syllabus_point', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Syllabus')),
            ],
        ),
    ]
