# Generated by Django 3.0.7 on 2020-08-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0012_auto_20200817_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
