# Generated by Django 3.0.6 on 2020-05-21 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0012_studentsyllabusmanualstudentrecord_studentsyllabusmanualteacherrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsyllabusmanualstudentrecord',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentsyllabusmanualteacherrecord',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
