# Generated by Django 3.0.7 on 2020-09-07 03:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0013_suspension_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspension',
            name='teachinggroups',
            field=models.ManyToManyField(blank=True, to='GreenPen.TeachingGroup'),
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_type', models.CharField(max_length=256)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Mistake')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='mistakes',
            field=mptt.fields.TreeManyToManyField(blank=True, to='GreenPen.Mistake'),
        ),
    ]
