# Generated by Django 3.0.6 on 2020-05-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0013_auto_20200521_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='sitting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Sitting'),
        ),
    ]
