# Generated by Django 3.0.7 on 2020-10-27 02:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0014_auto_20200907_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='GreenPen.TTSlot'),
        ),
    ]
