# Generated by Django 3.0.6 on 2020-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0015_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='identifier',
            field=models.CharField(blank=True, help_text='This would be a sub point number, e.g. if this is 1.1.1 Blah blah, enter 1', max_length=20, null=True),
        ),
    ]
