# Generated by Django 3.0.7 on 2020-12-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0016_examtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenPen.ExamType'),
        ),
    ]
