# Generated by Django 3.0.6 on 2020-05-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0016_auto_20200522_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
