# Generated by Django 3.0.7 on 2020-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0017_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
