# Generated by Django 3.0.6 on 2020-05-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0017_mark_student_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='sitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.Sitting'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsyllabusassessmentrecord',
            unique_together={('student', 'syllabus_point', 'sitting')},
        ),
    ]
