# Generated by Django 3.0.6 on 2020-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0018_auto_20200522_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
