# Generated by Django 3.1.5 on 2021-01-08 05:27
# Uncomment this line to autocomplete in IDE (must comment out again before
# Running migrations to prevent errors!)
from GreenPen.models import Exam, ExamType
from django.db import migrations


def set_default_exam_type(apps, schema_editor):
    # ExamsType = apps.get_model('GreenPen', 'ExamsType')
    # Exams = apps.get_model('GreenPen', 'Exams')
    default_type, created = ExamType.objects.get_or_create(type='Not set')
    Exam.objects.filter(type__isnull=True).update(type=default_type.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0018_exam_year'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(set_default_exam_type, reverse_code=migrations.RunPython.noop),
]