# Generated by Django 3.1.5 on 2021-01-11 06:57

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GreenPen', '0019_auto_20210108_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='GQuizExam',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GreenPen.exam')),
                ('response_sheet_url', models.URLField(help_text='This must be the URL for the Google Sheet containing your responses')),
                ('response_sheet_key', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('GreenPen.exam',),
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='mark_scheme_url',
            field=models.URLField(blank=True, help_text='Location of the mark scheme.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='share_mark_scheme',
            field=models.BooleanField(default=False, help_text='Make this mark scheme available to students.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(help_text='Year group sitting this exam', null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('open_to_all', models.BooleanField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('url', models.URLField(blank=True, null=True)),
                ('allowed_groups', models.ManyToManyField(to='GreenPen.TeachingGroup')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenPen.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='GQuizQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GreenPen.question')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.gquizexam')),
            ],
            bases=('GreenPen.question',),
        ),
        migrations.CreateModel(
            name='GQuizMark',
            fields=[
                ('mark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GreenPen.mark')),
                ('student_response', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('teacher_response', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gcquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPen.gquizquestion')),
            ],
            bases=('GreenPen.mark',),
        ),
    ]
