# Generated by Django 3.0.6 on 2020-05-26 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0019_auto_20200522_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsyllabusmanualstudentrecord',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentsyllabusmanualteacherrecord',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
