# Generated by Django 3.1.5 on 2021-01-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0020_auto_20210111_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gquizmark',
            name='gcquestion',
        ),
        migrations.RemoveField(
            model_name='gquizquestion',
            name='quiz',
        ),
    ]
