# Generated by Django 3.0.6 on 2020-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0020_auto_20200526_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinggroup',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
