# Generated by Django 3.1.5 on 2021-01-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0021_auto_20210111_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='GQuizSitting',
            fields=[
                ('sitting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GreenPen.sitting')),
                ('scores_sheet_url', models.URLField(blank=True, null=True)),
                ('scores_sheet_key', models.CharField(max_length=1000)),
            ],
            bases=('GreenPen.sitting',),
        ),
    ]
