# Generated by Django 3.1.5 on 2021-01-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0022_gquizsitting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gquizexam',
            old_name='response_sheet_url',
            new_name='master_form_url',
        ),
        migrations.RemoveField(
            model_name='gquizexam',
            name='response_sheet_key',
        ),
    ]
