# Generated by Django 3.1.5 on 2021-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0023_auto_20210111_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='gquizexam',
            name='master_response_sheet_url',
            field=models.URLField(help_text='This must be the URL for the Google Sheet containing your responses', null=True),
        ),
        migrations.AddField(
            model_name='gquizquestion',
            name='google_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gquizexam',
            name='master_form_url',
            field=models.URLField(help_text='This must be the URL for the Google Form containing your questions'),
        ),
        migrations.AlterField(
            model_name='gquizsitting',
            name='scores_sheet_key',
            field=models.CharField(help_text='This is the ID field of the Google Sheet with your answers on it.', max_length=1000),
        ),
    ]
