# Generated by Django 3.1.5 on 2021-01-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0024_auto_20210113_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gquizsitting',
            name='scores_sheet_key',
            field=models.CharField(help_text='This is the ID field of the Google Sheet with your answers on it.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gquizsitting',
            name='scores_sheet_url',
            field=models.URLField(null=True),
        ),
    ]
