# Generated by Django 3.1.5 on 2021-01-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0025_auto_20210113_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='gquizsitting',
            name='importing',
            field=models.BooleanField(default=False),
        ),
    ]
