# Generated by Django 3.1.5 on 2021-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0026_gquizsitting_importing'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='on_role',
            field=models.BooleanField(default=True),
        ),
    ]
