# Generated by Django 3.1.5 on 2021-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0029_set_tg_sims_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinggroup',
            name='use_for_exams',
            field=models.BooleanField(default=True, help_text="If you have mutliple identical groups, e.g. same A-level class taught by two different teachers, you will need to create three groups: one for each teacher, and one shared one. Use the teacher groups for timetabling and lesson monitoring, and the shared one for all exams. The'Use for exams' flag should be set for the exam class."),
        ),
    ]
