# Generated by Django 3.1.5 on 2021-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0030_teachinggroup_use_for_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinggroup',
            name='linked_groups',
            field=models.ManyToManyField(blank=True, to='GreenPen.TeachingGroup'),
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='students',
            field=models.ManyToManyField(blank=True, to='GreenPen.Student'),
        ),
        migrations.AlterField(
            model_name='teachinggroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='GreenPen.Teacher'),
        ),
    ]
