# Generated by Django 3.1.5 on 2021-02-17 05:42

from django.db import migrations


def fix_missing_student_ids(apps, schema_editor):
    Student = apps.get_model("GreenPen", "Student")
    User = apps.get_model("auth", "User")
    Mark = apps.get_model("GreenPen", "Mark")

    # delete students without a user:
    Student.objects.filter(user__isnull=True).delete()

    ss = Student.objects.filter(student_id__isnull=True)
    for s in ss:
        u = s.user
        clash_s = Student.objects.filter(user=u)
        if clash_s.count() == 1:
            continue
        if clash_s.count() > 2:
            print("Problems with " + str(u))
        s0 = clash_s[0]
        s1 = clash_s[1]

        m0 = Mark.objects.filter(student=s0)
        m1 = Mark.objects.filter(student=s1)

        if m0.count() == 0:
            s0.delete()

        elif m1.count() == 0:
            s1.delete()

        else:
            print("Both students have marks: " + str(u))


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0031_auto_20210216_0917'),
    ]

    operations = [
        migrations.RunPython(fix_missing_student_ids)
    ]
