# Generated by Django 3.1.5 on 2021-02-17 06:41

from django.db import migrations

def fix_missing_student_ids(apps, schema_editor):
    Student = apps.get_model("GreenPen", "Student")

    # delete students without an id:
    Student.objects.filter(student_id__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0033_auto_20210217_0547'),
    ]

    operations = [
        migrations.RunPython(fix_missing_student_ids)
    ]
