# Generated by Django 3.1.5 on 2021-02-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0034_auto_20210217_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitting',
            options={'permissions': [('create_any_sitting', 'Can create a sitting for any classgroup')]},
        ),
    ]
