# Generated by Django 3.1.7 on 2021-03-15 03:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0035_auto_20210221_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.resourcetype'),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='icon',
            field=models.CharField(help_text='Enter a font-awesome string here.', max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='resource',
            name='syllabus',
            field=mptt.fields.TreeManyToManyField(to='GreenPen.Syllabus'),
        ),
    ]
