# Generated by Django 3.1.7 on 2021-03-15 05:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0036_auto_20210315_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='open_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='resource',
            name='syllabus',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.syllabus'),
        ),
    ]
