# Generated by Django 3.1.7 on 2021-03-15 06:51

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0037_auto_20210315_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='resource',
            name='syllabus',
            field=mptt.fields.TreeManyToManyField(to='GreenPen.Syllabus'),
        ),
    ]
