# Generated by Django 3.1.7 on 2021-03-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0038_auto_20210315_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='GreenPen.TeachingGroup'),
        ),
    ]
