# Generated by Django 3.1.7 on 2021-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0039_auto_20210317_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='eligible_for_self_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gquizsitting',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gquizsitting',
            name='self_assessment',
            field=models.BooleanField(default=False, help_text='Set to yes if this is a student self-assessment attempt'),
        ),
    ]
