# Generated by Django 3.1.7 on 2021-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0040_auto_20210407_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='self_assessed',
            field=models.BooleanField(default=False),
        ),
    ]
