# Generated by Django 3.1.7 on 2021-05-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0041_sitting_self_assessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='tier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
