# Generated by Django 3.1.7 on 2021-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0042_syllabus_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['identifier']},
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='self_assessed',
        ),
        migrations.AddField(
            model_name='sitting',
            name='imported',
            field=models.BooleanField(default=True, help_text='Set to true after results have been imported.'),
        ),
        migrations.AlterField(
            model_name='gquizsitting',
            name='order',
            field=models.IntegerField(blank=True, help_text='Used for multiple attempts at same self-assessment quiz', null=True),
        ),
    ]
