# Generated by Django 3.1.7 on 2021-05-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0043_auto_20210518_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenPen.gquizexam'),
        ),
    ]
