# Generated by Django 3.1.7 on 2021-08-10 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0046_auto_20210804_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 10, 0, 951494)),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('order', 'name', 'year')},
        ),
    ]
