# Generated by Django 3.1.7 on 2021-08-10 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0047_auto_20210810_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 6, 32, 38, 473655)),
        ),
        migrations.AlterUniqueTogether(
            name='calendaredperiod',
            unique_together={('tt_slot', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('order', 'name', 'year')},
        ),
    ]
