# Generated by Django 3.1.7 on 2021-08-10 07:10

import datetime
from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0048_auto_20210810_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, to='GreenPen.Resource'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='syllabus',
            field=mptt.fields.TreeManyToManyField(blank=True, to='GreenPen.Syllabus'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 7, 10, 36, 656935)),
        ),
        migrations.AlterUniqueTogether(
            name='ttslot',
            unique_together={('day', 'period', 'year'), ('year', 'order')},
        ),
    ]
