# Generated by Django 3.1.7 on 2021-08-13 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0049_auto_20210810_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='group_lock',
            field=models.BooleanField(default=False, help_text='Lock this so that only stuents in your class may see it.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='open_to_all',
            field=models.BooleanField(default=True, help_text='Allow students to see this resource.'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 54, 19, 670784)),
        ),
    ]
