# Generated by Django 3.1.7 on 2021-10-13 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0050_auto_20210813_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('studentsyllabusassessmentrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GreenPen.studentsyllabusassessmentrecord')),
            ],
            bases=('GreenPen.studentsyllabusassessmentrecord',),
        ),
        migrations.AddField(
            model_name='sitting',
            name='require_self_assessment',
            field=models.BooleanField(default=False, help_text='Set to true to force students to complete a self-assessment of the spec points before makrs can be recoreded.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='syllabus',
            field=mptt.fields.TreeManyToManyField(to='GreenPen.Syllabus'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 1, 56, 31, 676096)),
        ),
    ]
