# Generated by Django 3.2.8 on 2021-10-25 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0053_alter_sitting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='self_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='teacher_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentsyllabusassessmentrecord',
            name='sitting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.sitting'),
        ),
        migrations.DeleteModel(
            name='SelfAssessment',
        ),
    ]
