# Generated by Django 3.2.8 on 2021-10-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0055_alter_sitting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsyllabusassessmentrecord',
            old_name='most_recent',
            new_name='most_recent_examined',
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='most_recent_self',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='most_recent_teacher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
