# Generated by Django 3.2.8 on 2021-10-25 07:56
#from GreenPen.models import StudentSyllabusAssessmentRecord
from django.db import migrations

def set_dates(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    StudentSyllabusAssessmentRecord = apps.get_model("GreenPen", "StudentSyllabusAssessmentRecord")
    for record in StudentSyllabusAssessmentRecord.objects.all():
        record.created = record.sitting.date
        record.save()


class Migration(migrations.Migration):

    dependencies = [
    ('GreenPen', '0059_auto_20211025_0756'),
]
    operations = [
        migrations.RunPython(set_dates),
    ]