# Generated by Django 3.2.8 on 2021-11-01 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0060_auto_20211025_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsyllabusassessmentrecord',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
