# Generated by Django 3.2.8 on 2021-11-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPen', '0061_alter_studentsyllabusassessmentrecord_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsyllabusassessmentrecord',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsyllabusassessmentrecord',
            name='sitting',
            field=models.ForeignKey(blank=True, help_text='If this is an exam-assessed record, we must have the exam related to it.', null=True, on_delete=django.db.models.deletion.CASCADE, to='GreenPen.sitting'),
        ),
    ]
